site_name: Ad Omnia
site_description: Informatics Engineering Project 2026/2027 - University of Aveiro
site_url: https://ad-omnia.github.io/micro-site/
repo_url: https://github.com/Ad-Omnia/micro-site
repo_name: Ad-Omnia/micro-site

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/home.js

theme:
  name: material
  language: en
  favicon: assets/logo-colour-black.svg
  custom_dir: overrides
  logo: assets/logo-colour-black.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.sections
    - navigation.top
    - content.code.copy
  font:
    text: Lato
    code: Roboto Mono
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # Ir descomentando/expandindo à medida que as páginas forem criadas

nav:
  - Documentation: documentation.md
  - Journey: journey.md
  - Milestones:
      - MS1 - Fase de Inception:
          - Descrição do projeto: milestones/ms1-inception/descricao-projeto.md
          - Calendário do projeto: milestones/ms1-inception/calendario.md
          - Plano de comunicação: milestones/ms1-inception/plano-comunicacao.md
      - MS2 - Fase de Elaboration:
          - Em breve: milestones/ms2-elaboration/em-breve.md
      - MS3 - Fase de Construction:
          - Em breve: milestones/ms3-construction/em-breve.md
      - MS4 - Fase de Transition:
          - Em breve: milestones/ms4-transition/em-breve.md
      - Calendário geral: milestones/calendario-geral.md
  - Minutes:
    - Minute 1: minutes\2026-09-23_Minute1_AdOmnia.md
  - Team: team.md
  # - Arquitetura: arquitetura.md
  # - Relatórios e apresentações: relatorios.md

copyright: "© 2026 Ad Omnia · University of Aveiro"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Ad-Omnia
