site_name: Ad Omnia
site_description: Informatics Engineering Project 2026/2027 - University of Aveiro
site_url: https://ad-omnia.github.io/
repo_url: https://github.com/Ad-Omnia/ad-omnia.github.io
repo_name: Ad-Omnia/ad-omnia.github.io

hooks:
  - hooks/minutes.py
  - hooks/milestones.py
  - hooks/journey.py
  - hooks/footer.py

watch:
  - hooks

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/home.js
  - javascripts/nav.js
  - javascripts/deck.js

theme:
  name: material
  language: en
  favicon: assets/logo-colour-black.svg
  custom_dir: overrides
  logo: assets/logo-colour-black.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - content.code.copy
  font:
    text: Lato
    code: Roboto Mono
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: false
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Documentation: documentation.md
  - Journey: journey.md
  - Milestones:
      - milestones/index.md
  - Minutes:
    - minutes/index.md
  - Team: team.md
  # - Architecture: architecture.md
  # - Reports and Presentations: reports.md

copyright: "© 2026 Ad Omnia · University of Aveiro"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Ad-Omnia
